[versions]
androidCore = "1.17.0"
androidGradlePlugin = "8.13.2"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
androidTestJunit = "1.3.0"
appcompat = "1.7.1"
coil = "3.3.0"
constraintlayout = "2.2.1"
coreTesting = "2.2.0"
daggerHilt = "2.59.1"
espresso = "3.7.0"
junit = "4.13.2"
kotlin = "2.3.10"
kotlinCoroutinesTest = "1.10.2"
ksp = "2.3.5"
ktlint = "0.51.0-FINAL"
lifecycle = "2.10.0"
material = "1.13.0"
mockk = "1.14.9"
moshi = "1.15.2"
navigation = "2.9.4"
okhttp3 = "5.3.2"
paging = "3.4.0"
retrofit2 = "3.0.0"
room = "2.8.4"
testCore = "1.7.0"

[libraries]
android-gradlePluginz = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-arch-coreTesting = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-lifecycle-livedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-navigationSafeArgsPluginz = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidx-navigation-navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-paging-pagingCommon = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-pagingRuntimeKtx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-room-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-roomPaging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-roomTesting = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "testCore" }
androidx-test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "testCore" }
androidx-test-espresso-espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }
androidx-test-ext-junitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidTestJunit" }

coil3-coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil3-networkOkhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

google-dagger-hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
google-dagger-hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "daggerHilt" }
google-dagger-hiltAndroidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "daggerHilt" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlin-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutinesTest" }
kotlin-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesTest" }
kotlin-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutinesTest" }
kotlin-gradlePluginz = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

ksp-gradlePluginz = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

mockk-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

squareup-moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
squareup-moshi-moshiKotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
squareup-okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
squareup-retrofit2-converterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2" }
squareup-retrofit2-converterScalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit2" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigationSafeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
